apiVersion: v1
data:
  nginx.conf: |
    events {}
    http {
      log_format  main  '$remote_addr $request $http_jwtscope $cookie_jwtscope';
      access_log  /dev/stdout  main;
      server {
        listen 80;
        location / {
          proxy_pass http://target-svc:80;
        }
      }
    }
kind: ConfigMap
metadata:
  name: gw-nginx-conf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: webapp
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /etc/nginx
              name: gw-nginx-conf
      volumes:
        - configMap:
            name: gw-nginx-conf
          name: gw-nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: webapp

