apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: nic
spec:
  host: nic.example.com
  upstreams:
  - name: target-v1
    service: target-v1-0
    port: 80
  - name: target-v2-timeout
    service: target-v2-0-timeout
    port: 80
    healthCheck:
      enable: true
      interval: 5s
      fails: 3
      passes: 3
      port: 80
      statusMatch: "! 400-599"
      #mandatory: true
      #persistent: true
  - name: target-v2-rst
    service: target-v2-0-rst
    port: 81
  routes:
  - path: /v1
    action:
      pass: target-v1
  - path: /v2-timeout
    action:
      pass: target-v2-timeout
    errorPages:
    - codes: [502]
      redirect:
        code: 301
        url: ${scheme}://nic.example.com/v1
