apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: webapp
spec:
  host: webapp.example.com
  policies:
  - name: jwt-policy
  upstreams:
  - name: webapp-svc
    service: webapp-svc
    port: 80
  routes:
  - path: /
    action:
      proxy:
        upstream: webapp-svc
        requestHeaders:
          pass: true
          set:
          - name: jwtscope
            value: ${jwt_claim_scope}
