apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: webapp
spec:
  host: webapp.example.com
  upstreams:
  - name: webapp-svc
    service: webapp-svc
    port: 80
  routes:
  - path: /
    action:
      pass: webapp-svc
